### ISSUE TITLE
Pipe Closed/Command execution failed: No space left on device

### ISSUE THREAD

**Issue by jitterdev** [pcal43/fastback#191]
im getting this issue on my modded server when i try to restore a backup:
[error](https://mclo.gs/WWNDBMP)
> java.io.IOException: Pipe closed

> org.eclipse.jgit.api.errors.TransportException: No space left on device

However I have plenty of storage allocated to the server in Pterodactyl Panel
![image](https://user-images.githubusercontent.com/64605731/227795370-82941d93-0ce3-4f05-b592-47a93d556b94.png)
And the node the server is running on has plenty of storage.
![image](https://user-images.githubusercontent.com/64605731/227795394-6744f9ab-e496-4037-bcdc-5a70da77cc71.png)

[Here's the full latest log](https://mclo.gs/epxPiyf)

**Comment by pcal43** [comment]
most likely it's running out of temp space and `/tmp` is on a different volume.

in any case, pretty sure this is a disk management issue, not a bug.

**Comment by jitterdev** [comment]
> most likely it's running out of temp space and `/tmp` is on a different volume.
> 
> in any case, pretty sure this is a disk management issue, not a bug.

Could the problem be that the server is running inside a Docker container?

Is there a way I could instead just download the snapshots that FastBack makes and then upload them to the server manually?

**Comment by pcal43** [comment]
> Could the problem be that the server is running inside a Docker container?

very possibly related.  depends on how your volume mapping is set up.

> Is there a way I could instead just download the snapshots

not sure I follow exactly.  fastback does it's thing in the `.git` directory under your world save directory.  and probably uses temp space as well.  no way to change that.

**Comment by jbrown1597** [comment]
Same issue. Also (not by choice) a Pterodactyl Panel user.

Attempting to narrow it down:
- 64gb: free on C: drive where Minecraft is
- 21gb: free on server
- 2gb: world size

Any suggestions? 
Additionally: Where are the /tmp files stored that you mentioned in your previous comment above? How can I relocate them?

**Comment by jbrown1597** [comment]
> most likely it's running out of temp space and `/tmp` is on a different volume.
> 
> in any case, pretty sure this is a disk management issue, not a bug.

Having the same issue. Also a Pterodactyl Panel user (not by choice).

Attempting to narrow down the cause:
- 64gb: free on C: drive where Minecraft is stored
- 21gb: free on server (Pterodactyl Panel)
- 2gb: world size
- 7 backups, none yet fully restored
- Can: Still make backups, local & server
- Can't: Use the delete & prune commands successfully.

My best guess, it has something to do with this: 
"_Note that files in the current world are never touched by restore; the restored snapshot is placed under your system temp directory (in server mode)._"

Perhaps what is out of memory is the temp folder & as a result, Pterodactyl Panel is just unable to recognize & display the server memory as full?

So - what's my best course of action then? Is it possible to delete 6 of the 7 backups? If I understood what I read correctly, since I have yet to fully restore anything, all the backups are merged together into one .tmp folder?
